### PR TITLE
Added threading back to the runserver.py

### PR DESCRIPTION
**Pull request by michaelclarkHID**

### CODE REVIEW

**Comment by michaelclarkHID** [comment]
Leave a comment

**Comment by michaelclarkHID** [comment]
Sorry - it pulled some different files

**Comment by yorek** [comment]
I saw that you closed the pull request. All the three changes makes perfectly sense. I would like to merge them into main branch, it that's ok for you

**Comment by michaelclarkHID** [comment]
Yes go ahead.

Sent from my iPhone

On Apr 22, 2017, at 9:54 PM, Davide Mauri <notifications@github.com<mailto:notifications@github.com>> wrote:


I saw that you closed the pull request. All the three changes makes perfectly sense. I would like to merge them into main branch, it that's ok for you

**Comment by yorek** [comment]
Done

**Pull request merged**
